name: retscan
description: A Flutter application for diagnosing ocular diseases from OCT and Retinal Scans.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.0.0
  flutter_bloc: ^8.0.1
  image_picker: ^1.1.1
  tensorflow_lite_flutter: ^2.0.1 # For integrating TensorFlow Lite models
  path_provider: ^2.0.8
  image: ^4.1.7  # Supports advanced image formats like TIFF, BMP, GIF
  archive: ^3.1.2  # For handling .gz files
  exif: ^3.3.0  # Specific for TIFF files if more control is needed over TIFF handling
  animate_do: ^3.3.4
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.3
  http_parser: ^4.0.2
  path: ^1.9.0
  url_launcher: ^6.2.6
  open_file: ^3.3.2
  flutter_cached_pdfview: ^0.4.0
  flutter_pdfview: ^1.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/icons/
    - lib/images/
